management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  tracing:
    sampling:
      probability: 1.0
    http:
      server:
        request:
          ignore-patterns:
            - /actuator/.*
            - /health.*
            - /metrics.*
  metrics:
    tags:
      application: ${spring.application.name}



